services:
  estoque_ti:
    container_name: estoque_ti
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - /var/www/dasssest.com/uploads/:/app/uploads:rw,z
    ports:
      - "2307:80"
    restart: unless-stopped